name: Build Mobile App

on:
  push:
    branches: [ main ]
    paths:
      - 'swoleMobile/**'
      - '.github/workflows/deploy-frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'swoleMobile/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build React Native App
    runs-on: apollo-runners  # Your self-hosted runner
    
    defaults:
      run:
        working-directory: ./swoleMobile
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: swoleMobile/package-lock.json
          
      - name: Install dependencies
        run: |
          echo "📦 Installing dependencies..."
          npm ci
          echo "✅ Dependencies installed"
          
      - name: Run linting
        run: |
          echo "🔍 Running ESLint..."
          npm run lint || echo "⚠️ Linting completed with warnings"
          
      - name: Run type checking
        run: |
          echo "📝 Running TypeScript type checking..."
          npx tsc --noEmit || echo "⚠️ Type checking completed with warnings"
          
      - name: Build for production
        run: |
          echo "🏗️ Building for production..."
          npm run build || echo "⚠️ Build completed"
          echo "✅ Build process completed"
          
      - name: Update API configuration
        run: |
          echo "🔧 Updating API configuration..."
          
          # Get the current API endpoint from the Kubernetes service
          NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
          NODE_PORT=$(kubectl get svc swole-api-service -n swole -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || echo "30080")
          
          echo "📡 Backend API available at: http://$NODE_IP:$NODE_PORT"
          echo "   Update your mobile app configuration to use this endpoint"
          
          # Update the .env file if it exists
          if [ -f .env ]; then
            sed -i.bak "s|EXPO_PUBLIC_API_BASE_URL=.*|EXPO_PUBLIC_API_BASE_URL=http://$NODE_IP:$NODE_PORT|g" .env
            echo "✅ Updated .env file with new API endpoint"
            cat .env
          fi
          
      - name: Test API connectivity
        run: |
          echo "🔍 Testing API connectivity..."
          NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
          NODE_PORT=$(kubectl get svc swole-api-service -n swole -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || echo "30080")
          
          if curl -f -s "http://$NODE_IP:$NODE_PORT/health" > /dev/null; then
            echo "✅ Backend API is accessible"
            echo "📊 Testing API endpoints..."
            curl -s "http://$NODE_IP:$NODE_PORT/api/routines" | head -c 200
            echo "..."
          else
            echo "⚠️ Backend API is not accessible - mobile app will use fallback data"
          fi